// Code generated by hertz generator.

package main

import (
	"ai-eino-interview-agent/internal/config"
	"ai-eino-interview-agent/internal/repository"
	"log"
	"os"
	"path/filepath"
	"runtime"

	"github.com/joho/godotenv"
)

func main() {
	// 1. 加载 .env 文件（如果存在）
	if err := godotenv.Load(); err != nil {
		log.Printf("Warning: Could not load .env file: %v", err)
		log.Println("Application will use system environment variables or config.yaml defaults")
	} else {
		log.Println("Successfully loaded .env file")
	}

	// 2. 加载配置文件
	// 获取配置文件路径（相对于 main.go 所在目录）
	configPath := findConfigFile()
	cfg, err := config.LoadConfig(configPath)
	if err != nil {
		log.Fatalf("Failed to load configuration: %v", err)
	}

	// 3. 展开配置中的环境变量引用（${VAR_NAME}）
	cfg.ExpandEnv()
	log.Println("Environment variables expanded in configuration")

	// 4. 初始化数据库
	log.Println("Initializing database connection...")
	err = repository.InitDatabase(cfg.Database)
	if err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}
	log.Println("Database initialized successfully")
}

// findConfigFile 查找配置文件路径
// 优先使用相对于 main.go 所在目录的 config.yaml
func findConfigFile() string {
	// 获取 main.go 源代码文件的路径
	_, currentFile, _, ok := runtime.Caller(0)
	if !ok {
		// 如果无法获取，尝试使用当前工作目录
		return "config.yaml"
	}

	// main.go 在 backend 目录下，config.yaml 也在 backend 目录下
	backendDir := filepath.Dir(currentFile)
	configPath := filepath.Join(backendDir, "config.yaml")

	// 检查文件是否存在
	if _, err := os.Stat(configPath); err == nil {
		return configPath
	}

	// 如果不存在，尝试当前工作目录
	if wd, err := os.Getwd(); err == nil {
		// 尝试 backend/config.yaml（从项目根目录运行）
		path1 := filepath.Join(wd, "backend", "config.yaml")
		if _, err := os.Stat(path1); err == nil {
			return path1
		}
		// 尝试 config.yaml（从 backend 目录运行）
		path2 := filepath.Join(wd, "config.yaml")
		if _, err := os.Stat(path2); err == nil {
			return path2
		}
	}

	// 默认返回相对于 main.go 的路径
	return configPath
}
