SELECT @@transaction_isolation;

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT * FROM `account`;

SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

START TRANSACTION;

SELECT * FROM `account`;

--

SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

--

SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;

START TRANSACTION;

SELECT * FROM `account`;

SELECT * FROM `account`;

--

SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;

SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;

START TRANSACTION;

SELECT * FROM `account` WHERE id = 3;

INSERT INTO `account` (id, name, money) value (3, '奶龙', 2000);

SELECT * FROM `account` WHERE id = 3;
