; 应用基础配置
app_name  = hachimi
; 日志级别可选值：DEBUG, INFO, WARNING, ERROR, FATAL
log_level = DEBUG

; ==============================================
; MySQL 数据库配置
; ==============================================
[mysql]
ip       = 127.0.0.1
port     = 3307
user     = leafevans
password = Qq20050514
database = test

; ==============================================
; Redis 缓存配置
; ==============================================
[redis]
ip   = 127.0.0.1
port = 6379
