// Code generated by hertz generator.

package mianshi

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mianshiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmianshianswerrecordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmianshievaluationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmianshirecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _answerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitmianshianswerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _endmianshiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sessionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsessionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _streamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _startmianshistreamMw() []app.HandlerFunc {
	// your code...
	return nil
}
