// Code generated by hertz generator.

package interviews

import (
	"context"

	interviews "ai-eino-interview-agent/api/model/interviews"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UploadResume .
// @router /api/resume/upload [POST]
func UploadResume(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviews.UploadResumeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interviews.UploadResumeResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetResume .
// @router /api/resume/:resume_id [GET]
func GetResume(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviews.GetResumeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interviews.GetResumeResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetUserResumes .
// @router /api/resume/list [GET]
func GetUserResumes(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviews.GetUserResumesRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interviews.GetUserResumesResponse)

	c.JSON(consts.StatusOK, resp)
}

// UpdateResume .
// @router /api/resume/:resume_id [PUT]
func UpdateResume(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviews.UpdateResumeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interviews.UpdateResumeResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteResume .
// @router /api/resume/:resume_id [DELETE]
func DeleteResume(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviews.DeleteResumeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interviews.DeleteResumeResponse)

	c.JSON(consts.StatusOK, resp)
}
