// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	interview "ai-eino-interview-agent/api/router/interview"
	interviews "ai-eino-interview-agent/api/router/interviews"
	mianshi "ai-eino-interview-agent/api/router/mianshi"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	mianshi.Register(r)

	interviews.Register(r)

	interview.Register(r)
}
