// Code generated by hertz generator.

package interviews

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserresumesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}
