// Code generated by hertz generator.

package interview

import (
	"context"

	mianshi "ai-eino-interview-agent/api/model/mianshi"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// StartMianshiStream .
// @router /api/mianshi/stream/start [POST]
func StartMianshiStream(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mianshi.MianshiStartInterviewRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(mianshi.MianshiStartInterviewResponse)

	c.JSON(consts.StatusOK, resp)
}

// SubmitMianshiAnswer .
// @router /api/mianshi/answer/submit [POST]
func SubmitMianshiAnswer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mianshi.MianshiSubmitInterviewAnswerRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(mianshi.MianshiSubmitInterviewAnswerResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetSession .
// @router /api/mianshi/session/info [GET]
func GetSession(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mianshi.MianshiGetSessionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(mianshi.MianshiGetSessionResponse)

	c.JSON(consts.StatusOK, resp)
}

// EndMianshi .
// @router /api/mianshi/interview/end [POST]
func EndMianshi(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mianshi.MianshiEndInterviewRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(mianshi.MianshiEndInterviewResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetMianshiEvaluation .
// @router /api/mianshi/evaluation [GET]
func GetMianshiEvaluation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mianshi.GetMianshiEvaluationRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(mianshi.GetMianshiEvaluationResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetMianshiAnswerRecord .
// @router /api/mianshi/answer-record [GET]
func GetMianshiAnswerRecord(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mianshi.GetMianshiAnswerRecordRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(mianshi.GetMianshiAnswerRecordResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetMianshiRecords .
// @router /api/mianshi/records [GET]
func GetMianshiRecords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mianshi.GetMianshiRecordsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(mianshi.GetMianshiRecordsResponse)

	c.JSON(consts.StatusOK, resp)
}
